import type { PronunciationAttempt } from "@/lib/pronunciation";
import type { TonePracticeAttempt } from "@/lib/tone-practice";

export type CoachStyle = "strict" | "friendly" | "playful" | "concise";
export type SessionMode = "daily" | "ask" | "quick";
export type MessageRole = "user" | "assistant" | "system";
export type SrsGrade = "again" | "hard" | "good" | "easy";
export type ModelSelectionMode = "auto" | "simple" | "complex" | "custom";

export interface SessionMetrics {
  durationSec?: number;
  tonePracticeAttempts?: TonePracticeAttempt[];
  /** Speaking practice attempts scored by the pronunciation coach. */
  pronunciationAttempts?: PronunciationAttempt[];
  /** Number of chat messages exchanged (user + assistant). */
  messageCount?: number;
  /** ISO timestamp of the last chat message. */
  lastActivityAt?: string;
  /** True when the server closed the session because the learner never pressed End. */
  autoClosed?: boolean;
  /** True when the summary was generated by the session summarizer agent. */
  summaryGenerated?: boolean;
}

export interface Profile {
  userId: string;
  goals: string[];
  level: "beginner" | "intermediate" | "advanced";
  interests: string[];
  timezone: string;
  coachStyle: CoachStyle;
  minutesPerDay: number;
  preferredSimpleModel: string;
  preferredComplexModel: string;
  /** Local hour (0-23) for the daily reminder; undefined/null means off. */
  reminderHour?: number | null;
  /** Local date (YYYY-MM-DD) of the last reminder sent, to avoid duplicates. */
  lastReminderDate?: string;
}

export interface SessionRecord {
  id: string;
  userId: string;
  mode: SessionMode;
  startedAt: string;
  endedAt?: string;
  summary?: string;
  durationSec?: number;
  metrics?: SessionMetrics;
}

export interface MessageRecord {
  id: string;
  sessionId: string;
  role: MessageRole;
  content: string;
  createdAt: string;
}

export interface MemoryItem {
  id: string;
  userId: string;
  type: "goal" | "preference" | "topic" | "vocab";
  key: string;
  value: string;
  confidence: number;
  createdAt: string;
  deletedAt?: string;
}

export interface SrsCard {
  id: string;
  userId: string;
  prompt: string;
  answer: string;
  hints: string[];
  tags: string[];
  ease: number;
  interval: number;
  nextDueAt: string;
  lastResult?: SrsGrade;
}

export interface VocabItem {
  id: string;
  userId: string;
  hanzi: string;
  pinyin?: string;
  english?: string;
  tags: string[];
  sourceSessionId?: string;
  createdAt: string;
}

export interface GrammarPointSignal {
  title: string;
  explanation: string;
  examples: string[];
  confidence: "high";
}

export interface GrammarPoint {
  id: string;
  userId: string;
  title: string;
  explanation: string;
  examples: string[];
  createdAt: string;
}

export interface AgentRun {
  id: string;
  userId: string;
  /** Absent for runs not tied to a chat session (planner, character cards). */
  sessionId?: string;
  nodeName: string;
  provider: string;
  tokens: number;
  latencyMs: number;
  costEstimate: number;
  createdAt: string;
}

export interface TutorStructuredResponse {
  keyPoints: string[];
  examples: string[];
  microExercise: string;
  suggestedReviewItems: string[];
  grammarPoints?: GrammarPointSignal[];
  /** 1-4 lowercase English words naming the theme of the reply; used to tag review cards. */
  topic?: string;
  answer: string;
}

export type PlanModality = "speaking" | "listening" | "reading" | "writing" | "review";
export type PlanItemStatus = "planned" | "completed" | "skipped";

export interface LearningPlanItem {
  /** 1-7 within the plan week. */
  day: number;
  /** ISO date (YYYY-MM-DD) in the learner's timezone. */
  date: string;
  title: string;
  /** Real-life outcome phrased as "I can ...". */
  canDo: string;
  lessonFocus: string;
  reviewFocus: string;
  modalities: PlanModality[];
  /** Why the planner chose this for this learner. */
  reason: string;
  estimatedMinutes: number;
  status: PlanItemStatus;
  completedSessionId?: string;
  note?: string;
}

export interface LearningPlan {
  id: string;
  userId: string;
  /** ISO date of day 1. */
  startDate: string;
  generatedAt: string;
  items: LearningPlanItem[];
  rationale: string;
  /** Snapshot of the inputs the planner saw, for transparency. */
  inputs: {
    level?: string;
    goals?: string[];
    weakAreas?: string[];
    dueCards?: number;
    vocabLearning?: number;
    recentSummaries?: string[];
    carriedOver?: string[];
  };
  model?: string;
}

export interface CharacterBreakdown {
  hanzi: string;
  pinyin: string;
  meaning: string;
  radical: string;
  radicalMeaning: string;
  components: string;
  mnemonic: string;
  strokeCount?: number;
}

export interface CharacterCard {
  /** The studied entry: 1-4 hanzi. */
  entry: string;
  pinyin: string;
  meaning: string;
  characters: CharacterBreakdown[];
  commonWords: Array<{ hanzi: string; pinyin: string; english: string }>;
  exampleSentence: { hanzi: string; pinyin: string; english: string };
  usageTip: string;
  generatedBy: string;
  generatedAt: string;
}

export interface StudiedEntry {
  entry: string;
  pinyin?: string;
  english?: string;
  /** Where the learner met this item. */
  source: "vocab" | "srs";
  lastResult?: SrsGrade;
  ease?: number;
  nextDueAt?: string;
  createdAt?: string;
}
