-- Rolling 7-day curriculum plans generated by the Curriculum Planner agent.
create table if not exists learn_chinese.learning_plans (
  id uuid primary key,
  user_id uuid not null,
  start_date date not null,
  generated_at timestamptz not null default now(),
  plan_json jsonb not null,
  model text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists learning_plans_user_generated_idx
  on learn_chinese.learning_plans (user_id, generated_at desc);

alter table learn_chinese.learning_plans enable row level security;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'learn_chinese' and tablename = 'learning_plans' and policyname = 'learning_plans_owner'
  ) then
    create policy learning_plans_owner on learn_chinese.learning_plans
      for all to authenticated
      using ((select auth.uid()) = user_id)
      with check ((select auth.uid()) = user_id);
  end if;
end
$$;

grant select, insert, update, delete on learn_chinese.learning_plans to authenticated;
grant all privileges on learn_chinese.learning_plans to service_role;
